#!/bin/sh

set -e

if [ ! -z "$DEBUG" ]; then
    set -x
fi

## install project
if [ ! -z "$PROJECT_VCS" ]; then 
    /usr/bin/composer config --global repositories.0 "{\"type\": \"vcs\", \"url\": \"$PROJECT_VCS\"}"
fi

if [ ! -z "$PROJECT_NAME" ]; then 
    /usr/bin/composer create-project \
      --stability=dev \
      --prefer-source \
      --no-interaction \
      --keep-vcs \
      $PROJECT_NAME $PROJECT_WORKDIR
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php "$@"
fi

